### ISSUE TITLE
Fix segmentation fault when running Kucher executable on Ubuntu 18.04

### ISSUE THREAD

**Issue by loicgilbert** [Zubax/kucher#37]
Running Kucher executable on Ubuntu 18.04 creates a segfault error. This happens for Kucher versions already released on https://files.zubax.com/products/com.zubax.kucher/, and on current developing versions. 
It might come from StaticX submodule, because running pyinstaller independently from `build_linux.sh` creates an operational executable.

**Comment by pavel-kirienko** [comment]
The solution I suggested: set up the CI to run the build against Ubuntu 16.04 so that the resulting binary is linked against an older version of libc. See https://github.com/pyinstaller/pyinstaller/wiki/FAQ section "Under Linux, I get runtime dynamic linker errors, related to libc. What should I do?". While doing this, we should watch out for https://github.com/Zubax/kucher/issues/1.

**Comment by loicgilbert** [comment]
Software is already building on Ubuntu 16.04 on the CI (it’s the oldest version available). I have tested the executable on an Ubuntu 18.04 virtual machine and no error. Also working on Mint 18.2.

**Comment by pavel-kirienko** [comment]
Cool. Okay. Let's just drop StaticX then.
